---
- name: Configure HTTPS on Web Server
  hosts: web_servers
  become: yes

  tasks:
    # 1. 컨테이너 이름으로 강제 삭제 (마운트 충돌/이름 충돌 방지)
    - name: Force stop and remove nginx_proxy container
      shell: |
        docker stop nginx_proxy || true
        docker rm nginx_proxy || true
      ignore_errors: yes

    # 2. 인증서 저장 폴더 생성
    - name: Create directory for certificates
      file:
        path: /home/vagrant/app/certs
        state: directory
        owner: vagrant
        group: vagrant

    # 3. index.html 파일 강제 생성 (디렉토리 마운트 오류 방지)
    - name: Ensure index.html is a file and contains correct content
      copy:
        dest: /home/vagrant/app/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head><title>Application Deployed</title></head>
          <body>
              <h1>Application Deployed Successfully via Ansible! (HTTPS)</h1>
              <p>This page is served by Nginx running inside a Docker container.</p>
          </body>
          </html>
        owner: vagrant
        group: vagrant
        mode: '0644'

    # 4. SSL 인증서 및 키 생성 (Self-Signed)
    - name: Generate Self-Signed SSL Certificate
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout /home/vagrant/app/certs/server.key
        -out /home/vagrant/app/certs/server.crt
        -subj "/C=FR/ST=Nouvelle-Aquitaine/L=Bordeaux/O=FilRouge/CN=web"
      args:
        creates: /home/vagrant/app/certs/server.crt

    # 5. Nginx 설정 파일 생성 (HTTPS 설정 포함)
    - name: Create Nginx configuration file (default.conf)
      copy:
        dest: /home/vagrant/app/default.conf
        content: |
          server {
              listen 80;
              server_name localhost;
              # HTTP로 접속하면 HTTPS로 리다이렉트
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name localhost;

              ssl_certificate /etc/nginx/certs/server.crt;
              ssl_certificate_key /etc/nginx/certs/server.key;

              location / {
                  root /usr/share/nginx/html;
                  index index.html;
              }
          }

    # 6. Docker Compose 파일 업데이트 (443 포트 및 볼륨 마운트 추가)
    - name: Update docker-compose.yml for HTTPS
      copy:
        dest: /home/vagrant/app/docker-compose.yml
        content: |
          version: '3.8'
          services:
            web_app:
              image: nginx:alpine
              container_name: nginx_proxy
              ports:
                - "80:80"
                - "443:443"
              volumes:
                - ./index.html:/usr/share/nginx/html/index.html
                - ./certs:/etc/nginx/certs
                - ./default.conf:/etc/nginx/conf.d/default.conf
              restart: always

    # 7. Docker Compose 재시작 (설정 적용)
    - name: Restart Docker containers to apply HTTPS
      command: docker-compose up -d --force-recreate
      args:
        chdir: /home/vagrant/app
      environment:
        HOME: /home/vagrant
